import type { GenTemplate } from './types';

/**
 * The first 24 official Seedance 2.5 showcase cases curated by EvoLink.
 * Preview clips are re-hosted on our R2; prompts are rewritten as reusable Remix briefs
 * and localized instead of copying the showcase page verbatim.
 * Source: https://evolink.ai/zh/seedance-2-5-prompts
 */
const PREVIEW_PREFIX = 'studio/gen-templates/video';

const videoTemplate = (
  id: string,
  category: string,
  title: string,
  slug: string,
  prompt: string,
  promptZh: string,
): GenTemplate => ({
  id,
  category,
  title,
  video: `${PREVIEW_PREFIX}/${slug}.mp4`,
  prompt,
  promptI18n: { zh: promptZh },
});

export const VIDEO_TEMPLATES: GenTemplate[] = [
  videoTemplate(
    'v01',
    'chatGen.ambience',
    'chatGen.steampunkMotionGraphics',
    'cinematic-steampunk-motion-graphics',
    'Create a seamless cinematic 3D journey through a miniature steampunk world. Fly past polished brass gears into a clockwork harbor with a wind-up sailing ship, then reveal an enormous glowing moon. Dense mechanical detail, volumetric light, continuous camera motion, premium motion-graphics finish.',
    '创作一段无缝衔接的电影感 3D 蒸汽朋克之旅。镜头穿过抛光黄铜齿轮，进入有发条帆船的机械港口，最后揭示一轮巨大的发光月亮。机械细节丰富、体积光明显、运镜连续，呈现高级动态图形质感。',
  ),
  videoTemplate(
    'v02',
    'chatGen.cameraMoves',
    'chatGen.crystalBallMatchCut',
    'crystal-ball-match-cut-montage',
    'Build a beat-synced match-cut montage around one crystal sphere that remains locked in the same screen position and sharp focus. Transform the background through eight radically different worlds while reflections, lighting, and camera energy adapt to each scene. Fast, precise transitions and a strong musical rhythm.',
    '围绕一颗始终固定在同一画面位置、保持清晰对焦的水晶球，制作随节拍卡点的匹配剪辑蒙太奇。背景依次切换八个风格完全不同的世界，反射、光线和镜头动势随场景变化。转场快速精准，音乐节奏强烈。',
  ),
  videoTemplate(
    'v03',
    'chatGen.product',
    'chatGen.brandWindowReveal',
    'brand-concept-window-reveal',
    'Create a cinematic brand-concept film in which the camera passes through a sequence of windows made from different materials and environments. Each opening reveals a new visual world, culminating in an extreme close-up of a human eye. Elegant visual metaphors, seamless transitions, restrained premium styling.',
    '创作一支电影感品牌概念短片，镜头连续穿过由不同材质和环境构成的窗户，每扇窗都通向一个新的视觉世界，最后落到人眼的极近特写。使用优雅的视觉隐喻、无缝转场和克制高级的品牌质感。',
  ),
  videoTemplate(
    'v04',
    'chatGen.ambience',
    'chatGen.multilingualKineticType',
    'multilingual-kinetic-typography',
    'Design a seamless kinetic-typography loop around the word “create” written in eleven languages. Give every language its own material world—ink, glass, metal, fabric, particles, liquid, or light—and morph one treatment naturally into the next. Bold legibility, tactile detail, rhythmic motion.',
    '围绕十一种语言书写的“创造”设计一段无缝循环动态文字。每种语言拥有独立的材质世界，例如墨水、玻璃、金属、织物、粒子、液体或光，并自然变形衔接到下一种效果。文字清晰有力、材质细腻、运动富有节奏。',
  ),
  videoTemplate(
    'v05',
    'chatGen.people',
    'chatGen.dreamyFashionBeauty',
    'dreamy-fashion-beauty-film',
    'Create a dreamy haute-couture beauty film with graceful model movement, luminous skin, floating fabric, soft bokeh, volumetric light, and silky motion-blur transitions. Alternate intimate beauty close-ups with sculptural full-body compositions. Hyper-real materials, romantic color, premium campaign finish.',
    '创作一支梦幻高定美妆大片，包含优雅的模特动作、通透肤质、漂浮面料、柔和光斑、体积光和丝滑的动感模糊转场。交替使用美妆特写与雕塑感全身构图，材质超写实、色彩浪漫，呈现顶级品牌广告质感。',
  ),
  videoTemplate(
    'v06',
    'chatGen.ambience',
    'chatGen.glowingJellyfishReef',
    'coral-reef-glowing-jellyfish',
    'A tranquil blue-hour coral reef with soft lavender bioluminescent jellyfish drifting slowly into frame. Sun rays ripple through clear water as tiny bubbles rise and gather into elegant letterforms before dissolving naturally. Meditative pacing, delicate underwater particles, seamless loop.',
    '宁静蓝调的珊瑚礁场景，淡紫色生物发光水母缓缓游入画面。阳光在清澈海水中摇曳，细小气泡上升并聚合成优雅文字，随后自然消散。节奏舒缓、水下粒子细腻，形成无缝循环。',
  ),
  videoTemplate(
    'v07',
    'chatGen.ambience',
    'chatGen.floatingDesertMuseum',
    'floating-desert-museum',
    'A cinematic art-film journey across a quiet golden desert toward a minimal white museum floating above the dunes. The camera glides through the architecture as a monumental wall slowly opens to reveal an endless blue sky. Warm natural light, restrained luxury, surreal scale, seamless movement.',
    '电影感艺术短片：镜头平稳穿过安静的金色沙漠，推进到漂浮在沙丘上的极简白色美术馆，再穿行于建筑内部，最后一面巨墙缓缓打开，露出无尽蓝天。暖色自然光、克制高级、超现实尺度、连续流畅运镜。',
  ),
  videoTemplate(
    'v08',
    'chatGen.people',
    'chatGen.desertFashionFilm',
    'desert-fashion-brand-film',
    'Create a high-fashion concept film with a model crossing monumental red dunes in wind-swept couture. Use precise editorial compositions, harsh sculptural sunlight, and slow confident movement. In the finale, pull back to break the fourth wall and reveal that the desert is displayed inside a giant LED virtual-production stage.',
    '创作一支高级时装概念短片，模特身着被风吹动的高定服装穿越宏大的赤色沙丘。使用精准的编辑式构图、雕塑感强光和缓慢自信的动作。结尾镜头拉远打破第四面墙，揭示沙漠其实位于巨型 LED 虚拟影棚中。',
  ),
  videoTemplate(
    'v09',
    'chatGen.people',
    'chatGen.pekingOperaHeritage',
    'peking-opera-heritage-film',
    'Tell a warm, restrained story of an elderly Peking-opera artisan passing technique and emotion to a young apprentice. Focus on hands preparing paint, embroidered costume details, quiet eye contact, and a final shared stage moment. Intimate cinema lighting, authentic workshop textures, respectful pacing.',
    '讲述一位年长京剧匠人将技艺与情感传递给年轻学徒的温暖克制故事。重点表现调制油彩的手、刺绣戏服细节、安静的眼神交流，以及最后共同登台的时刻。电影光线亲密、作坊质感真实、节奏尊重而从容。',
  ),
  videoTemplate(
    'v10',
    'chatGen.ambience',
    'chatGen.oceanCivilizationEpic',
    'oceanic-civilization-epic',
    'Create an epic science-fiction worldbuilding sequence that dives from a stormy ocean into a vast submerged civilization, passes monumental ruins and bioluminescent machines, then rises through the atmosphere into space. Immense scale, mysterious archaeology, cinematic contrast, one continuous sense of discovery.',
    '创作一段史诗科幻世界观镜头：从暴风海面潜入宏大的沉没文明，穿过巨型遗迹与生物发光机械，再冲出大气层进入太空。尺度震撼、考古感神秘、电影对比强烈，全程保持连续探索感。',
  ),
  videoTemplate(
    'v11',
    'chatGen.product',
    'chatGen.mechanicalFlowerBloom',
    'mechanical-flower-bloom',
    'Create a single continuous macro push through a metallic flower bud in darkness. Reveal intricate gears, glass petals, and luminous filaments as the mechanism awakens, then end on the fully opened flower sending a warm pulse of light outward. Premium product-film lighting, precise mechanical detail, smooth cinematic motion.',
    '一镜到底微距推进：从黑暗中的金属花苞进入精密齿轮、玻璃花瓣与发光丝线组成的内部结构，机械逐步苏醒，最后花朵完全绽放并向外扩散一圈暖光。高级产品广告光影，机械细节清晰，运镜流畅。',
  ),
  videoTemplate(
    'v12',
    'chatGen.bRoll',
    'chatGen.silkRoadPomegranate',
    'silk-road-pomegranate-journey',
    'Create a flat mineral-pigment animation tracing a pomegranate from soil to glass along the Silk Road. Let one red fruit travel through ancient orchards, caravan routes, patterned markets, and a final drink-pouring moment. Rock-painting texture, restrained parallax, regional ornament, warm historical storytelling.',
    '以岩彩平面动画讲述一颗石榴沿丝绸之路从土地走向杯中的旅程。让红色果实穿越古老果园、商队路线、纹样集市，最终进入倒入杯中的饮品。矿物颜料质感、克制视差、西域装饰与温暖历史叙事。',
  ),
  videoTemplate(
    'v13',
    'chatGen.cameraMoves',
    'chatGen.sixRoomsOneTake',
    'six-rooms-one-take',
    'A 30-second continuous tracking shot follows one character through six physically connected rooms. Each doorway transforms the production design, lighting, color palette, and emotion while the subject’s movement remains perfectly continuous. Choreographed camera blocking, invisible transitions, cinematic realism.',
    '30 秒一镜到底跟随同一人物连续穿过六个相连房间。每次经过门框，布景、光线、色彩与情绪都发生明显变化，但人物动作和镜头运动始终无缝衔接。精确调度、隐藏转场、电影级写实质感。',
  ),
  videoTemplate(
    'v14',
    'chatGen.bRoll',
    'chatGen.footballHistoryJourney',
    'football-3000-year-history',
    'Create a fast historical explainer in which one moving ball links three thousand years of football culture. Match-cut from ancient cuju through different civilizations, early organized matches, packed twentieth-century stadiums, and today’s game. Clear chronology, changing period art direction, energetic educational pacing.',
    '制作一段节奏明快的历史科普短片，用一颗持续运动的球串联三千年足球文化。从古代蹴鞠匹配剪辑到不同文明、早期正式比赛、二十世纪大型球场，再到现代足球。时间线清晰、年代美术不断变化、科普节奏有活力。',
  ),
  videoTemplate(
    'v15',
    'chatGen.product',
    'chatGen.coffeeMachineTutorial',
    'coffee-machine-tutorial',
    'Produce a concise step-by-step capsule coffee-machine tutorial. Show unpacking, tank installation, capsule loading, cup placement, brewing, and cleanup with clean close-ups, numbered callouts, reference-angle consistency, and calm instructional narration. Bright tabletop lighting and precise hand demonstrations.',
    '制作一段简洁的胶囊咖啡机分步教程，依次展示开箱、水箱安装、放入胶囊、摆放杯子、萃取与清洁。使用干净特写、步骤编号、统一参考角度和沉稳教学旁白，桌面光线明亮，手部演示准确。',
  ),
  videoTemplate(
    'v16',
    'chatGen.people',
    'chatGen.marketSeasonsOneTake',
    'lonely-woman-market-one-shot',
    'A continuous cinematic follow shot stays with a solitary woman moving through a crowded open-air market. Without cutting, the same street gradually shifts from day to night and cycles through spring, summer, autumn, and winter while her pace remains steady. Rich environmental storytelling and seamless temporal transitions.',
    '一镜到底跟随一位独自穿过露天集市的女子。镜头不中断，同一条街道在她稳定前行的过程中从白天过渡到夜晚，并依次经历春、夏、秋、冬。环境叙事丰富、情绪含蓄、时间与季节转换无缝。',
  ),
  videoTemplate(
    'v17',
    'chatGen.product',
    'chatGen.fruitBiscuitAd',
    'fruit-biscuit-product-ad',
    'Create a bright, colorful, rhythm-driven commercial for fruit-filled biscuits. Arrange products in satisfying geometric patterns, use punchy match cuts between flavors, and capture a slow-motion break that releases a vivid fruit center. Crisp macro texture, playful studio lighting, energetic pack-shot finish.',
    '创作一支明亮多彩、强节奏的果味夹心饼干广告。将产品排列成令人舒适的几何阵列，用有力的匹配剪辑切换不同口味，并以慢动作捕捉饼干折断、鲜艳果味夹心爆开的瞬间。微距质感清脆、棚拍光线活泼、结尾产品镜头有冲击力。',
  ),
  videoTemplate(
    'v18',
    'chatGen.product',
    'chatGen.desertLizardGrapefruit',
    'desert-lizard-grapefruit-ad',
    'Create a playful cinematic 3D beverage ad in which a sun-scorched desert horned lizard discovers a giant fresh grapefruit. The first drop of juice becomes a sparkling wave that floods the dry landscape and transforms it into a vibrant citrus world. Expressive character animation, tactile fruit detail, escalating spectacle.',
    '创作一支有趣的电影感 3D 饮品广告：快被晒干的沙漠角蜥发现一颗巨大的新鲜葡萄柚，第一滴果汁化作闪亮浪潮淹没干旱大地，并把环境变成鲜活的柑橘世界。角色表演生动、果肉细节真实、场面逐步升级。',
  ),
  videoTemplate(
    'v19',
    'chatGen.cameraMoves',
    'chatGen.youthRacingAnimation',
    'youth-racing-anime-film',
    'Create a cinematic 2D youth-racing short with a complete emotional arc told almost entirely through motion. Use high-speed side tracking, wheel and eye close-ups, wind-driven environment streaks, and one slow-motion orbit at the decisive overtaking moment. Hand-drawn energy, dynamic perspective, heartfelt finish.',
    '创作一支具有完整情绪弧线的电影感 2D 青春竞速短片，主要通过运动讲故事。使用高速侧向跟拍、车轮与眼睛特写、被风拉伸的环境线条，并在决定性超越瞬间加入一次慢动作环绕。手绘能量充沛、透视动态、结尾真挚。',
  ),
  videoTemplate(
    'v20',
    'chatGen.cameraMoves',
    'chatGen.fpvMultilingualGreetings',
    'fpv-drone-multilingual-greetings',
    'Design a single-take FPV descent from clouds through water reflections and into a glowing city. At each stage, natural formations, architecture, and light trails briefly compose the word “hello” in a different language before the camera continues downward. Precise flight path, seamless spatial transitions, uplifting global tone.',
    '设计一段一镜到底 FPV 下降飞行：从云层穿过水面倒影进入发光城市。每个阶段都由自然形态、建筑或光轨短暂拼出一种语言的“你好”，随后镜头继续下降。飞行路径精准、空间转场无缝、全球化氛围积极。',
  ),
  videoTemplate(
    'v21',
    'chatGen.people',
    'chatGen.flowerPassingThankYou',
    'flower-passing-thank-you',
    'A warm human-centered montage built around one flower passing hand to hand between people in different countries. Match its screen position and movement at every cut while each person says “thank you” in their local language. Natural expressions, intimate documentary light, hopeful emotional arc.',
    '以一朵鲜花为视觉线索的温暖真人蒙太奇：鲜花在不同国家的人们之间依次传递，每个人用当地语言说“谢谢”。每次切镜都保持鲜花的位置与运动方向一致，让交接形成无缝匹配转场。自然表情、亲密纪录片光线、情绪逐步升温。',
  ),
  videoTemplate(
    'v22',
    'chatGen.bRoll',
    'chatGen.energyBowVfxEdit',
    'energy-bow-vfx-edit',
    'Edit the source jungle action shot by adding a blue-white energy bow and luminous arrow to the performer’s hands. Track the original body motion and camera perspective exactly, preserve composition and timing, and add believable interactive light, particles, charge-up glow, and an energy trail on release.',
    '在原有丛林动作素材中，为人物双手加入蓝白色能量弓与发光箭矢。精确跟随原始身体动作与镜头透视，保持构图和时序不变，并加入可信的交互光、粒子、蓄能辉光以及释放时的能量拖尾。',
  ),
  videoTemplate(
    'v23',
    'chatGen.bRoll',
    'chatGen.droneRemovalEdit',
    'drone-object-removal-edit',
    'Cleanly remove the visible drone and foreground camera rail from the source wildlife shot. Reconstruct the giraffe, vegetation, ground texture, shadows, and parallax behind the removed objects while preserving the original camera movement, subject motion, color, grain, and depth of field.',
    '从原始野生动物镜头中干净移除可见无人机和前景摄影轨道。自然补全被遮挡的长颈鹿、植被、地面纹理、阴影与视差，同时保持原始运镜、主体动作、色彩、颗粒和景深。',
  ),
  videoTemplate(
    'v24',
    'chatGen.people',
    'chatGen.martialArtsRestyleEdit',
    'martial-arts-restyle-edit',
    'Restyle the source sparring footage into a tense pre-duel scene from a classical martial-arts film. Replace the modern environment with an atmospheric historical courtyard, transform both performers into period costumes with cold weapons, and preserve their exact blocking, timing, camera motion, and facial identity.',
    '将原始对练素材重塑为古典武侠片中决斗前的试探场景。把现代环境替换成有氛围的古代庭院，为双方更换时代服装与冷兵器，同时严格保留原始走位、动作时序、运镜和人物身份。',
  ),
];
