/**
 * Audio-track orchestration (workbench hook, same deps-object pattern as use-clip-insert):
 *  - mount music files (upload / assets / generated bytes) as clips on the music lane: blob src +
 *    sig + OPFS (remote/generated sources may also use the cloud vault), initial level from measured loudness (clip sits AUDIO_AUTO_UNDER_DB
 *    below the narration; silently falls back to the default when measurement fails);
 *  - keep the engine's clip channel in sync with comp.audioTracks (per-clip envelope/source-time
 *    closures from the same pure fns export uses);
 *  - draft restore: revive dead blob srcs from OPFS/cloud by sig (recoverLocalClips analog);
 *  - generation: POST /api/studio/music → bytes → the same mount path as upload.
 */

import { useEffect, useMemo, useRef, useState, type MutableRefObject, type SetStateAction } from 'react';
import {
  type AudioClip,
  type Composition,
  audioClipGainAt,
  audioClipId,
  audioClipSrcTimeAt,
  patchAudioClip,
  totalDuration,
} from '@pireel/studio-engine/composition';
import { studioProviders } from '@pireel/studio-engine/providers';
import { toast } from '@pireel/ui/toast';
import type { EngineAudioClip, VideoTrackEngine } from './video-track-engine';
import { decodeAudioFile, decodeVideoAudio } from './audio-decode';
import { bgmAutoVolumeDb, measureBufferLoudnessDb } from './loudness';
import { fileSig } from './media';
import { loadLocalVideo, saveLocalVideo } from './local-media';
import { t } from './i18n';

export interface AudioTracksDeps {
  comp: Composition;
  compRef: MutableRefObject<Composition>;
  setComp: (action: SetStateAction<Composition>) => void;
  videoFileRef: MutableRefObject<File | null>;
  videoSigRef: MutableRefObject<string | null>;
  videoEngineRef: MutableRefObject<VideoTrackEngine | null>;
  /** Inserted-clip bytes (key = blob url), so the scene rail can draw each source's own waveform. */
  clipFilesRef: MutableRefObject<Map<string, File>>;
  /** Playhead (edited seconds): new clips land here — "insert at the playhead" is the NLE default. */
  tRef: MutableRefObject<number>;
  pickFile: (accept: string) => Promise<File | null>;
  backupMediaToCloud: (file: File, sig: string, kind: 'video' | 'clip') => void;
  pushUndoSnapshot: () => void;
}

export function useAudioTracks(deps: AudioTracksDeps) {
  const { comp, compRef, setComp, videoFileRef, videoSigRef, videoEngineRef, clipFilesRef, tRef, pickFile, backupMediaToCloud, pushUndoSnapshot } = deps;
  /** Mounted bytes per clip sig (blob src dies on refresh; the File here is the live handle). */
  const audioFilesRef = useRef<Map<string, File>>(new Map());
  const [audioFileRev, setAudioFileRev] = useState(0);
  /** Peak envelope per VIDEO source ('main' / insert-clip url) for the scene rail's audio strip: the video
   *  track has its own sound, and the rail should show it. Measured lazily off the same extract+decode the
   *  loudness pass uses; failures (no audio track) just leave the strip empty. */
  const [sourcePeaks, setSourcePeaks] = useState<Map<string, { peaks: Float32Array; durationSec: number }>>(new Map());
  const srcTriedRef = useRef<Set<string>>(new Set());
  /** Peak envelope per sig for the lane waveform (computed from the same decode as the loudness measure;
   *  in-memory only — recomputed when bytes are recovered, never persisted). */
  const [audioPeaks, setAudioPeaks] = useState<Map<string, Float32Array>>(new Map());
  /** Main-narration loudness cache (extract+decode is seconds on long videos — measure once per source). */
  const narrDbRef = useRef<{ sig: string; db: number | null } | null>(null);
  const recoverTriedRef = useRef<Set<string>>(new Set());

  const narrationDb = async (): Promise<number | null> => {
    const f = videoFileRef.current;
    if (!f) return null;
    const sig = videoSigRef.current ?? fileSig(f);
    if (narrDbRef.current?.sig === sig) return narrDbRef.current.db;
    let db: number | null = null;
    try {
      const buf = await decodeVideoAudio(f);
      db = buf ? measureBufferLoudnessDb(buf) : null;
    } catch {
      /* no audio track / decode failure → default clip level */
    }
    narrDbRef.current = { sig, db };
    return db;
  };

  /** Whether a clip's bytes are playable right now (mounted File, or a non-blob URL the element can stream). */
  const clipUsable = (c: AudioClip): boolean => (c.sig != null && audioFilesRef.current.has(c.sig)) || !c.src.startsWith('blob:');

  /** Absolute-peak envelope over the whole file (~100 points/s, capped) for the lane waveform — dense
   *  enough that a zoomed-in chip still gets a distinct bar per column instead of repeating buckets. */
  const peaksOf = (buf: AudioBuffer): Float32Array => {
    const n = Math.min(30000, Math.max(200, Math.round(buf.duration * 100)));
    const ch0 = buf.getChannelData(0);
    const ch1 = buf.numberOfChannels > 1 ? buf.getChannelData(1) : ch0;
    const out = new Float32Array(n);
    const step = ch0.length / n;
    for (let i = 0; i < n; i++) {
      const a = Math.floor(i * step);
      const b = Math.min(ch0.length, Math.floor((i + 1) * step));
      let peak = 0;
      // stride-sample long windows: a 5-minute track has ~1M samples per bucket, full scan is wasteful
      const stride = Math.max(1, Math.floor((b - a) / 400));
      for (let j = a; j < b; j += stride) {
        const v = Math.max(Math.abs(ch0[j]!), Math.abs(ch1[j]!));
        if (v > peak) peak = v;
      }
      out[i] = peak;
    }
    return out;
  };

  /** Mount music bytes as a NEW clip on the lane: measure → initial level → OPFS → comp.audioTracks.
   *  A supplied sig means this is a project-local asset: metadata syncs, bytes stay on-device. */
  const mountAudioFile = async (file: File, label?: string, opts?: { startSec?: number; sig?: string | null }) => {
    let durationSec: number | undefined;
    let volumeDb: number | undefined;
    let peaks: Float32Array | undefined;
    try {
      const buf = await decodeAudioFile(file);
      durationSec = Math.round(buf.duration * 10) / 10;
      peaks = peaksOf(buf);
      const clipDb = measureBufferLoudnessDb(buf);
      const narrDb = await narrationDb();
      if (clipDb != null && narrDb != null) volumeDb = bgmAutoVolumeDb(narrDb, clipDb);
    } catch {
      toast.error(t('workbench.musicDecodeFailed'));
      return;
    }
    const sig = opts?.sig ?? fileSig(file);
    const url = URL.createObjectURL(file);
    audioFilesRef.current.set(sig, file);
    setAudioFileRev((v) => v + 1);
    if (peaks) setAudioPeaks((m) => new Map(m).set(sig, peaks!));
    void saveLocalVideo(file, sig); // the OPFS library is byte-agnostic despite the name
    if (!opts?.sig) backupMediaToCloud(file, sig, 'clip');
    pushUndoSnapshot();
    // Drop position when dragged onto the lane, otherwise the playhead (NLE default: new clips land where you are)
    const at = opts?.startSec ?? tRef.current;
    const startSec = at > 0.05 ? Math.round(at * 10) / 10 : undefined;
    const clip: AudioClip = {
      id: audioClipId(),
      src: url,
      sig,
      label: label ?? file.name.replace(/\.[a-z0-9]+$/i, ''),
      ...(durationSec != null ? { durationSec } : {}),
      ...(volumeDb != null && volumeDb !== 0 ? { volumeDb } : {}),
      ...(startSec != null ? { startSec } : {}),
    };
    setComp((c) => ({ ...c, audioTracks: [...(c.audioTracks ?? []), clip] }));
    return clip.id;
  };

  /** Mount from an asset URL (assets-panel "use as BGM" / timeline drop), then the exact upload path
   *  (loudness auto-level included). Byte lanes, best first: a known sig reads the on-device file
   *  (handle/OPFS — identity preserved, zero fetch); blob: URLs fetch directly (they are document-
   *  local, the server proxy can never resolve them); remote URLs go through the same-origin proxy. */
  const mountAudioFromUrl = async (url: string, label?: string, opts?: { startSec?: number; sig?: string | null }) => {
    if (opts?.sig) {
      const f = await loadLocalVideo(opts.sig);
      if (f) return mountAudioFile(f, label, opts);
    }
    const r = url.startsWith('blob:')
      ? await fetch(url).catch(() => null)
      : await fetch(`/api/media/fetch?url=${encodeURIComponent(url)}`).catch(() => null);
    if (!r?.ok) {
      toast.error(t('workbench.musicGenFailed'));
      return;
    }
    const type = r.headers.get('content-type')?.split(';')[0] || 'audio/mpeg';
    const name = (() => {
      try {
        return decodeURIComponent(new URL(url).pathname.split('/').pop() || '') || 'bgm';
      } catch {
        return 'bgm';
      }
    })();
    return mountAudioFile(new File([await r.blob()], name, { type }), label, opts);
  };

  const uploadAudio = async () => {
    const f = await pickFile('audio/*');
    if (!f) return;
    await mountAudioFile(f);
    // Audio CONTENT lives in the assets library (classification: content vs settings) — register the
    // upload there too, best-effort: the clip already works from local bytes if this fails.
    void (async () => {
      try {
        const { url } = await studioProviders().uploads.upload(f, { contentType: f.type || 'audio/mpeg', filename: f.name });
        await fetch('/api/me/uploads', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ kind: 'audio', url, label: f.name, role: 'general', mime: f.type, byte_size: f.size }),
        });
      } catch {
        /* asset registration is a bonus, not a dependency */
      }
    })();
  };

  const removeClip = (id: string) => {
    pushUndoSnapshot();
    setComp((c) => {
      const next = (c.audioTracks ?? []).filter((x) => x.id !== id);
      if (next.length) return { ...c, audioTracks: next };
      const { audioTracks: _drop, ...rest } = c;
      return rest as Composition;
    });
  };

  const patchClip = (id: string, patch: Partial<Pick<AudioClip, 'startSec' | 'volumeDb' | 'fadeInSec' | 'fadeOutSec' | 'speed' | 'inSec' | 'outSec' | 'muted'>>) => {
    setComp((c) => ({ ...c, audioTracks: (c.audioTracks ?? []).map((x) => (x.id === id ? patchAudioClip(x, patch) : x)) }));
  };

  /** Solo (monitoring only): while set, ONLY that clip is audible in preview — every other clip and the
   *  footage's own sound go quiet. Deliberately not part of the composition: it answers "what does this one
   *  sound like", not "what should the video be", so it never persists and never reaches export. Muting a
   *  clip, which IS a decision about the video, lives on the clip (AudioClip.muted). */
  const [soloId, setSoloId] = useState<string | null>(null);
  const soloRef = useRef<string | null>(null);
  soloRef.current = soloId;
  useEffect(() => {
    if (soloId && !(comp.audioTracks ?? []).some((c) => c.id === soloId)) setSoloId(null); // clip gone → drop it
  }, [comp.audioTracks, soloId]);

  /** Engine specs from current state (panel edits land in comp immediately, so there is no separate
   *  preview override to thread through — the effect below respecs from whatever comp says). */
  const engineSpecs = (): EngineAudioClip[] => {
    const c = compRef.current;
    const total = totalDuration(c);
    return (c.audioTracks ?? [])
      .filter(clipUsable)
      .map((clip) => ({
        id: clip.id,
        url: clip.src,
        speed: Math.max(0.5, Math.min(2, clip.speed ?? 1)),
        gainAt: (tt: number) => (soloRef.current && soloRef.current !== clip.id ? 0 : audioClipGainAt(clip, tt, total)),
        srcTimeAt: (tt: number) => audioClipSrcTimeAt(clip, tt),
      }));
  };

  // Engine sync: respec on any clip/timeline/bytes change (same-url respec swaps only closures — no reload).
  useEffect(() => {
    videoEngineRef.current?.setAudioClips(engineSpecs());
    videoEngineRef.current?.setMonitorMuteVideo(!!soloId); // solo silences the footage too, or it isn't solo
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [comp.audioTracks, comp.shots, comp.video, audioFileRev, soloId]);

  // Draft restore: dead blob src + sig → OPFS, then cloud vault; remap to a fresh blob URL.
  useEffect(() => {
    for (const clip of comp.audioTracks ?? []) {
      const sig = clip.sig;
      if (!sig || audioFilesRef.current.has(sig) || !clip.src.startsWith('blob:')) continue;
      if (recoverTriedRef.current.has(sig)) continue;
      recoverTriedRef.current.add(sig);
      void (async () => {
        let f = await loadLocalVideo(sig);
        if (!f) f = await studioProviders().vault.fetch(sig);
        if (!f) return; // stays unusable → panel offers re-pick
        void saveLocalVideo(f, sig);
        audioFilesRef.current.set(sig, f);
        setAudioFileRev((v) => v + 1);
        void decodeAudioFile(f)
          .then((buf) => setAudioPeaks((m) => new Map(m).set(sig, peaksOf(buf))))
          .catch(() => {});
        const url = URL.createObjectURL(f);
        setComp((c) => ({ ...c, audioTracks: (c.audioTracks ?? []).map((x) => (x.sig === sig ? { ...x, src: url } : x)) }));
      })();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [comp.audioTracks]);

  // Scene-rail waveforms: measure each video source once (main + every inserted clip that has bytes)
  useEffect(() => {
    const jobs: { key: string; file: File }[] = [];
    const vf = videoFileRef.current;
    if (vf) jobs.push({ key: 'main', file: vf });
    for (const sh of comp.shots ?? []) {
      if (!sh.src) continue;
      const f = clipFilesRef.current.get(sh.src);
      if (f) jobs.push({ key: sh.src, file: f });
    }
    for (const j of jobs) {
      const tag = `${j.key}:${fileSig(j.file)}`;
      if (srcTriedRef.current.has(tag)) continue;
      srcTriedRef.current.add(tag);
      void (async () => {
        try {
          const buf = await decodeVideoAudio(j.file);
          if (buf) setSourcePeaks((m) => new Map(m).set(j.key, { peaks: peaksOf(buf), durationSec: buf.duration }));
        } catch {
          /* source without an audio track / decode failure: the strip just stays empty */
        }
      })();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [comp.shots, comp.video]);

  /** Export payload (bytes per usable clip); clips with missing bytes are skipped (panel shows them). */
  const audioForExport = (): { clip: AudioClip; file: File }[] | null => {
    const out: { clip: AudioClip; file: File }[] = [];
    for (const clip of compRef.current.audioTracks ?? []) {
      const f = clip.sig ? audioFilesRef.current.get(clip.sig) : undefined;
      if (f) out.push({ clip, file: f });
    }
    return out.length ? out : null;
  };

  /** Hosted music generation. Returns the stored url and leaves it in the assets library (the route
   *  registers it) — placing it on the lane is a separate, explicit action, exactly like a generated image. */
  const generateAudioAsset = async (prompt: string, durationSec: number): Promise<string> => {
    const r = await fetch('/api/studio/music', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ prompt, duration_sec: durationSec }),
    });
    if (!r.ok) {
      const msg = (await r.json().catch(() => null)) as { error?: string } | null;
      throw new Error(msg?.error || t('workbench.musicGenFailed'));
    }
    const { url } = (await r.json()) as { url: string };
    return url;
  };

  /** True peak per clip sig (linear 0..1), for the panel's clipping warning — computed off the same peak
   *  envelope the waveform draws, so it costs one pass over a few thousand floats per newly mounted clip. */
  const clipPeaks = useMemo(() => {
    const out = new Map<string, number>();
    for (const [sig, peaks] of audioPeaks) {
      let m = 0;
      for (const v of peaks) if (v > m) m = v;
      out.set(sig, m);
    }
    return out;
  }, [audioPeaks]);

  return {
    audioFilesRef,
    audioPeaks,
    clipPeaks,
    soloId,
    setSoloId,
    sourcePeaks,
    clipUsable,
    uploadAudio,
    removeClip,
    patchClip,
    audioForExport,
    mountAudioFile,
    mountAudioFromUrl,
    generateAudioAsset,
  };
}
