/** Interface Current v2: real product surfaces, state change, people, system depth, resolution. */
import { type Block, mk } from './shared';

const root = (id: string) => `
#${id} .ic{position:absolute;inset:0;overflow:hidden;background:var(--paper);color:var(--fg);font-family:var(--font-body);}
#${id} .head{font-family:var(--font-head);font-weight:900;letter-spacing:-.045em;}
#${id} .num{font-family:var(--font-num);font-variant-numeric:tabular-nums;}
#${id} .micro{font-family:var(--font-num);font-size:18px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;}
#${id} .screen{position:absolute;background:#edf3f5;color:#172029;border:8px solid #29343d;box-shadow:var(--shadow);overflow:hidden;}
#${id} .screen .nav{position:absolute;left:0;top:0;bottom:0;width:150px;background:#182129;}
#${id} .screen .bar{position:absolute;left:190px;right:45px;height:18px;background:#bec9cd;border-radius:2px;}
#${id} .screen .bar.hot{background:var(--accent);}
#${id} .signal{position:absolute;height:10px;background:var(--accent);transform-origin:left center;box-shadow:var(--glow);}
#${id} .signal::after{content:'';position:absolute;right:-2px;top:-8px;border-left:18px solid var(--accent);border-top:13px solid transparent;border-bottom:13px solid transparent;}
#${id} .status{display:inline-flex;gap:12px;align-items:center;padding:13px 18px;border:2px solid var(--line);font-family:var(--font-num);font-size:18px;letter-spacing:.1em;}
#${id} .status i{width:12px;height:12px;border-radius:50%;background:var(--accent);}
#${id} [data-edit]{outline:none;}`;

export const cover: () => Block = () => mk('cv_ic2', '封面', (id) => `
<div class="ic cover"><div class="screen"><i class="nav"></i><i class="bar a"></i><i class="bar hot b"></i><div class="result"></div></div><div class="person"><i></i><b></b></div><i class="signal"></i><div class="title head" data-edit>界面流</div><div class="english num">INTERFACE CURRENT</div><div class="thesis micro">PERSON / PRODUCT / STATE / RESULT</div></div>
<style>${root(id)}
#${id} .cover .screen{right:80px;top:120px;width:950px;height:730px;transform:perspective(1200px) rotateY(-7deg);}#${id} .cover .bar.a{top:105px;width:430px;}#${id} .cover .bar.b{top:155px;width:610px;}#${id} .result{position:absolute;left:190px;right:55px;top:230px;bottom:55px;background:linear-gradient(135deg,#c6d4d7,#f8fbfb);border:4px solid #27323a;}#${id} .person{position:absolute;right:780px;bottom:-50px;width:360px;height:700px;}#${id} .person i{position:absolute;left:90px;top:0;width:180px;height:210px;border-radius:48%;background:#9a6b51;}#${id} .person b{position:absolute;left:10px;top:200px;width:340px;height:520px;border-radius:150px 150px 0 0;background:#485866;}#${id} .cover>.signal{left:770px;top:520px;width:400px;}#${id} .title{position:absolute;left:85px;top:240px;font-size:190px;line-height:.9;}#${id} .english{position:absolute;left:95px;top:520px;font-size:30px;font-weight:900;letter-spacing:.19em;}#${id} .thesis{position:absolute;left:95px;bottom:80px;color:var(--accent);}
</style>`, (id) => `tl.from('#${id} .screen',{x:180,autoAlpha:0,duration:.36},0);tl.from('#${id} .person',{y:100,autoAlpha:0,duration:.3},.16);tl.from('#${id} .title,#${id} .english,#${id} .thesis',{x:-50,autoAlpha:0,duration:.24,stagger:.07},.28);tl.from('#${id} .signal',{scaleX:0,duration:.25},.48);`);

export const blocks: Record<string, () => Block> = {
  'product-thesis': () => mk('ic_thesis', 'product-thesis', (id) => `
<div class="ic thesis"><div class="human"><div class="person"><i></i><b></b></div></div><div class="copy"><span class="micro">PRODUCT THESIS / REAL FRICTION</span><h2 class="head" data-edit>工作没有离开人<br/><b>系统只是接住它</b></h2><p data-edit>从真实操作和真实结果开始，不从抽象科技开始。</p><span class="status"><i></i>READY FOR INPUT</span></div><i class="edge"></i></div>
<style>${root(id)}
#${id} .human{position:absolute;right:0;top:0;width:790px;height:1080px;background:linear-gradient(145deg,#bac5ca,#e8edef 60%,#6c7a82);}#${id} .person{position:absolute;left:190px;top:170px;width:430px;height:830px;}#${id} .person i{position:absolute;left:110px;width:210px;height:240px;border-radius:48%;background:#a9785e;}#${id} .person b{position:absolute;left:20px;top:225px;width:390px;height:600px;border-radius:180px 180px 0 0;background:#35454f;}#${id} .copy{position:absolute;left:80px;top:85px;width:1050px;}#${id} .copy h2{margin-top:140px;font-size:105px;line-height:.98;}#${id} .copy h2 b{color:var(--accent);}#${id} .copy p{margin-top:70px;width:730px;font-size:28px;line-height:1.55;color:var(--muted);}#${id} .copy .status{margin-top:70px;}#${id} .edge{position:absolute;left:1090px;top:0;width:14px;height:820px;background:var(--accent);}
</style>`, (id) => `tl.from('#${id} .human',{x:170,duration:.34},0);tl.from('#${id} .edge',{scaleY:0,transformOrigin:'top',duration:.27},.14);tl.from('#${id} .copy>*',{x:-45,autoAlpha:0,duration:.24,stagger:.08},.25);`),

  'live-interface': () => mk('ic_live', 'live-interface', (id) => `
<div class="ic live"><div class="screen"><i class="nav"></i><div class="crumb num">PROJECT / REVIEW / CURRENT</div><i class="bar a"></i><i class="bar b hot"></i><div class="workspace"><div class="cursor"></div><div class="selection"></div></div></div><div class="note"><span class="micro">LIVE INTERFACE / INPUT → RESPONSE</span><h2 class="head" data-edit>让真实界面<br/><b>自己证明变化</b></h2><span class="status"><i></i>STATE CHANGED</span></div><i class="signal"></i></div>
<style>${root(id)}
#${id} .live .screen{left:70px;top:80px;width:1230px;height:920px;}#${id} .crumb{position:absolute;left:190px;top:45px;font-size:18px;}#${id} .live .bar.a{top:110px;width:610px;}#${id} .live .bar.b{top:155px;width:430px;}#${id} .workspace{position:absolute;left:190px;right:50px;top:220px;bottom:60px;background:#c8d4d7;}#${id} .selection{position:absolute;left:170px;top:150px;width:510px;height:310px;border:10px solid var(--accent);background:#eaf2f3;}#${id} .cursor{position:absolute;left:650px;top:430px;width:0;height:0;border-left:25px solid #101820;border-top:38px solid transparent;transform:rotate(-28deg);}#${id} .note{position:absolute;left:1370px;top:130px;width:460px;}#${id} .note h2{margin-top:135px;font-size:72px;line-height:1;}#${id} .note h2 b{color:var(--accent);}#${id} .note .status{margin-top:90px;color:var(--accent-2);}#${id} .live>.signal{left:1180px;top:700px;width:390px;}
</style>`, (id) => `tl.from('#${id} .screen',{x:-130,autoAlpha:0,duration:.34},0);tl.from('#${id} .selection',{scale:.8,autoAlpha:0,duration:.28},.3);tl.from('#${id} .cursor',{x:120,y:90,duration:.38},.38);tl.from('#${id} .signal',{scaleX:0,duration:.25},.56);tl.from('#${id} .note>*',{x:45,autoAlpha:0,duration:.23,stagger:.07},.5);`),

  'state-transition': () => mk('ic_state', 'state-transition', (id) => `
<div class="ic state"><span class="micro">STATE TRANSITION / WHAT PERSISTED?</span><h2 class="head" data-edit>同一个位置<br/><b>只改变一个状态</b></h2><div class="states"><div class="before"><span class="num">BEFORE / PENDING</span><div class="panel"><i class="bar"></i><i class="bar"></i><i class="wait"></i></div></div><i class="signal"></i><div class="after"><span class="num">AFTER / VERIFIED</span><div class="panel"><i class="bar"></i><i class="bar hot"></i><b>✓</b></div></div></div></div>
<style>${root(id)}
#${id} .state>.micro{position:absolute;left:80px;top:65px;}#${id} .state>h2{position:absolute;left:80px;top:150px;font-size:88px;line-height:.98;}#${id} .state>h2 b{color:var(--accent);}#${id} .states{position:absolute;left:80px;right:80px;bottom:75px;height:560px;}#${id} .before,#${id} .after{position:absolute;top:0;width:720px;height:520px;}#${id} .before{left:0;}#${id} .after{right:0;}#${id} .states span{display:block;margin-bottom:22px;font-size:19px;letter-spacing:.12em;}#${id} .panel{position:relative;height:440px;background:#eaf0f2;color:#172029;border:6px solid #303a42;}#${id} .panel .bar{position:relative;display:block;margin:75px 70px 0;width:470px;height:22px;background:#aebdc2;}#${id} .panel .hot{background:var(--accent);}#${id} .wait{position:absolute;right:75px;bottom:70px;width:90px;height:90px;border:12px solid #aebdc2;border-right-color:var(--accent);border-radius:50%;}#${id} .panel b{position:absolute;right:70px;bottom:55px;width:115px;height:115px;border-radius:50%;background:var(--accent-2);display:grid;place-items:center;font-size:72px;color:#101810;}#${id} .states>.signal{left:760px;top:260px;width:230px;}
</style>`, (id) => `tl.from('#${id} h2,#${id}>.micro',{x:-45,autoAlpha:0,duration:.24,stagger:.08},0);tl.from('#${id} .before',{x:-100,autoAlpha:0,duration:.3},.22);tl.from('#${id} .signal',{scaleX:0,duration:.28},.43);tl.from('#${id} .after',{x:100,autoAlpha:0,duration:.3},.58);tl.from('#${id} .after b',{scale:0,duration:.2},.78);`),

  'human-machine': () => mk('ic_human', 'human-machine', (id) => `
<div class="ic human-machine"><div class="room"><div class="person"><i></i><b></b></div><div class="device"></div></div><div class="response"><span class="micro">HUMAN / ATTENTION / FEEDBACK</span><h2 class="head" data-edit>人在看结果<br/><b>不是在装点界面</b></h2><div class="wave"></div><span class="status"><i></i>HANDOFF RECEIVED</span></div><i class="signal"></i></div>
<style>${root(id)}
#${id} .room{position:absolute;left:0;top:0;width:1050px;height:1080px;background:linear-gradient(135deg,#818e94,#dbe2e4 58%,#303b42);overflow:hidden;}#${id} .person{position:absolute;left:220px;top:170px;width:430px;height:820px;}#${id} .person i{position:absolute;left:110px;width:210px;height:240px;border-radius:48%;background:#a9785e;}#${id} .person b{position:absolute;left:20px;top:225px;width:390px;height:600px;border-radius:180px 180px 0 0;background:#334852;}#${id} .device{position:absolute;right:60px;top:350px;width:420px;height:280px;background:#111a20;border:18px solid #2c3840;transform:skewY(-5deg);}#${id} .response{position:absolute;left:1130px;top:115px;width:690px;}#${id} .response h2{margin-top:130px;font-size:85px;line-height:.98;}#${id} .response h2 b{color:var(--accent);}#${id} .wave{margin-top:90px;width:620px;height:150px;background:repeating-linear-gradient(90deg,var(--accent) 0 7px,transparent 7px 28px);clip-path:polygon(0 45%,5% 35%,10% 60%,15% 20%,20% 72%,25% 38%,30% 55%,35% 30%,40% 65%,45% 42%,50% 70%,55% 25%,60% 58%,65% 36%,70% 75%,75% 40%,80% 60%,85% 33%,90% 55%,95% 40%,100% 50%,100% 100%,0 100%);}#${id} .response .status{margin-top:70px;}#${id} .human-machine>.signal{left:930px;top:560px;width:300px;}
</style>`, (id) => `tl.from('#${id} .room',{x:-160,duration:.35},0);tl.from('#${id} .signal',{scaleX:0,duration:.27},.28);tl.from('#${id} .response>*',{x:55,autoAlpha:0,duration:.24,stagger:.08},.38);tl.from('#${id} .wave',{scaleX:0,transformOrigin:'left',duration:.32},.58);`),

  'system-depth': () => mk('ic_depth', 'system-depth', (id) => `
<div class="ic depth"><span class="micro">SYSTEM DEPTH / ONLY WHEN IT EXPLAINS</span><div class="layers"><div class="l front"><b class="head" data-edit>界面</b><span>用户可见状态</span></div><div class="l middle"><b class="head" data-edit>任务</b><span>正在处理</span></div><div class="l back"><b class="head" data-edit>来源</b><span>已记录证据</span></div><i class="signal a"></i><i class="signal b"></i></div><div class="copy"><h2 class="head" data-edit>进入系统深处<br/><b>必须带回答案</b></h2><p>每一层都对应真实层级，不使用匿名科技背景。</p></div></div>
<style>${root(id)}
#${id} .depth>.micro{position:absolute;left:80px;top:65px;}#${id} .layers{position:absolute;left:80px;top:150px;width:1000px;height:800px;perspective:1200px;}#${id} .l{position:absolute;width:650px;height:420px;padding:55px;border:5px solid var(--accent);background:#18222c;box-shadow:var(--shadow);}#${id} .l.front{left:0;top:330px;z-index:3;}#${id} .l.middle{left:190px;top:175px;z-index:2;opacity:.88;}#${id} .l.back{left:380px;top:20px;z-index:1;opacity:.62;}#${id} .l b{font-size:75px;}#${id} .l span{display:block;margin-top:175px;font-size:24px;color:var(--muted);}#${id} .layers .signal{width:260px;z-index:4;}#${id} .layers .a{left:640px;top:545px;transform:rotate(-30deg);}#${id} .layers .b{left:810px;top:345px;transform:rotate(-30deg);}#${id} .copy{position:absolute;left:1220px;top:220px;width:610px;}#${id} .copy h2{font-size:79px;line-height:1;}#${id} .copy h2 b{color:var(--accent);}#${id} .copy p{margin-top:70px;font-size:27px;line-height:1.55;color:var(--muted);}
</style>`, (id) => `tl.from('#${id} .l',{x:-100,y:80,autoAlpha:0,duration:.28,stagger:.14},0);tl.from('#${id} .signal',{scaleX:0,duration:.24,stagger:.16},.42);tl.from('#${id} .copy>*',{x:50,autoAlpha:0,duration:.24,stagger:.09},.48);`),

  'resolved-flow': () => mk('ic_resolved', 'resolved-flow', (id) => `
<div class="ic resolved"><div class="screen"><i class="nav"></i><i class="bar a"></i><i class="bar hot b"></i><div class="done">✓</div><span class="num">DELIVERED / 14:32</span></div><div class="copy"><span class="micro">RESOLVED FLOW / USEFUL OUTCOME</span><h2 class="head" data-edit>结果回到工作里<br/><b>系统安静下来</b></h2><p data-edit>结束在真实输出，不结束在无限加载。</p><span class="status ok"><i></i>VERIFIED RESULT</span></div><i class="lime"></i></div>
<style>${root(id)}
#${id} .resolved{background:var(--panel-2);color:#172029;}#${id} .resolved .screen{left:80px;top:100px;width:930px;height:820px;}#${id} .resolved .bar.a{top:110px;width:500px;}#${id} .resolved .bar.b{top:165px;width:620px;}#${id} .done{position:absolute;left:330px;top:285px;width:280px;height:280px;border-radius:50%;background:var(--accent-2);display:grid;place-items:center;font-size:190px;font-weight:900;}#${id} .resolved .screen>span{position:absolute;left:190px;bottom:55px;font-size:20px;}#${id} .resolved .copy{position:absolute;left:1120px;top:150px;width:690px;}#${id} .resolved .copy h2{margin-top:145px;font-size:86px;line-height:.98;}#${id} .resolved .copy h2 b{color:#087d69;}#${id} .resolved .copy p{margin-top:65px;font-size:28px;line-height:1.5;}#${id} .resolved .status{margin-top:70px;border-color:#172029;}#${id} .resolved .status i{background:#087d69;}#${id} .lime{position:absolute;right:0;bottom:0;width:660px;height:36px;background:var(--accent-2);}
</style>`, (id) => `tl.from('#${id} .screen',{x:-130,autoAlpha:0,duration:.34},0);tl.from('#${id} .done',{scale:0,duration:.28,ease:'back.out(1.4)'},.28);tl.from('#${id} .copy>*',{x:55,autoAlpha:0,duration:.24,stagger:.08},.35);tl.from('#${id} .lime',{scaleX:0,transformOrigin:'right',duration:.27},.62);`),
};
