/** Concept Atlas v2: source-led inquiry, routes, scale, correction, synthesis. */
import { type Block, mk } from './shared';

const root = (id: string) => `
#${id} .ca{position:absolute;inset:0;overflow:hidden;background:var(--paper);color:var(--fg);font-family:var(--font-body);}
#${id} .head{font-family:var(--font-head);font-weight:900;letter-spacing:-.045em;}
#${id} .num{font-family:var(--font-num);font-variant-numeric:tabular-nums;}
#${id} .micro{font-family:var(--font-num);font-size:18px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;}
#${id} .photo{position:absolute;overflow:hidden;background:linear-gradient(145deg,#c7c0af,#eee8db 58%,#9ca398);}
#${id} .object{position:absolute;background:#a98763;border:5px solid var(--fg);box-shadow:var(--shadow);}
#${id} .route{position:absolute;height:12px;background:var(--accent);transform-origin:left center;}
#${id} .route::after{content:'';position:absolute;right:-2px;top:-10px;border-left:22px solid var(--accent);border-top:16px solid transparent;border-bottom:16px solid transparent;}
#${id} .label{position:absolute;padding:12px 18px;background:var(--paper);border:3px solid var(--fg);font-size:23px;font-weight:850;}
#${id} [data-edit]{outline:none;}`;

export const cover: () => Block = () => mk('cv_ca2', '封面', (id) => `
<div class="ca cover"><div class="photo"><i class="object"></i><i class="route"></i><span class="label">看见关系</span></div><div class="title head" data-edit>概念图谱</div><div class="english num">CONCEPT ATLAS</div><div class="thesis micro">SOURCE / RELATION / REVISION / SYNTHESIS</div><i class="coral"></i></div>
<style>${root(id)}
#${id} .cover .photo{right:0;top:0;width:940px;height:1080px;}#${id} .cover .object{left:270px;top:270px;width:370px;height:460px;border-radius:48% 48% 14% 14%;}#${id} .cover .route{left:110px;top:530px;width:620px;transform:rotate(-12deg);}#${id} .cover .label{left:90px;top:390px;}#${id} .title{position:absolute;left:90px;top:260px;width:820px;font-size:178px;line-height:.9;}#${id} .english{position:absolute;left:98px;top:620px;font-size:31px;font-weight:900;letter-spacing:.2em;}#${id} .thesis{position:absolute;left:98px;bottom:85px;}#${id} .coral{position:absolute;left:780px;top:0;width:18px;height:760px;background:var(--accent-2);}
</style>`, (id) => `tl.from('#${id} .photo',{x:180,duration:.36,ease:'power3.out'},0);tl.from('#${id} .title,#${id} .english,#${id} .thesis',{x:-50,autoAlpha:0,duration:.25,stagger:.07},.18);tl.from('#${id} .route',{scaleX:0,duration:.28},.4);tl.from('#${id} .coral',{scaleY:0,transformOrigin:'top',duration:.25},.48);`);

export const blocks: Record<string, () => Block> = {
  'question-field': () => mk('ca_question', 'question-field', (id) => `
<div class="ca question"><div class="photo"><div class="person"><i></i><b></b></div></div><div class="copy"><span class="micro">QUESTION / BEGIN WITH THE SOURCE</span><h2 class="head" data-edit>为什么同一个动作<br/><b>会得到不同结果？</b></h2><p data-edit>先看见真实对象，再沿着关系寻找答案。</p></div><i class="route"></i><span class="label">从这里开始</span></div>
<style>${root(id)}
#${id} .question .photo{right:0;top:0;width:780px;height:1080px;}#${id} .person{position:absolute;left:160px;top:170px;width:430px;height:760px;}#${id} .person i{position:absolute;left:115px;top:0;width:210px;height:230px;border-radius:48%;background:#9e6c50;}#${id} .person b{position:absolute;left:20px;top:220px;width:390px;height:540px;border-radius:180px 180px 0 0;background:#405c53;}#${id} .copy{position:absolute;left:85px;top:90px;width:1010px;}#${id} .copy h2{margin-top:130px;font-size:104px;line-height:.98;}#${id} .copy h2 b{color:var(--accent);}#${id} .copy p{margin-top:70px;width:700px;font-size:29px;line-height:1.55;}#${id} .question>.route{left:890px;top:760px;width:470px;transform:rotate(-17deg);}#${id} .question>.label{left:810px;top:815px;}
</style>`, (id) => `tl.from('#${id} .photo',{x:160,duration:.34},0);tl.from('#${id} .copy>*',{x:-40,autoAlpha:0,duration:.24,stagger:.08},.18);tl.from('#${id} .route',{scaleX:0,duration:.28},.45);tl.from('#${id} .label',{autoAlpha:0,duration:.2},.65);`),

  'object-breakdown': () => mk('ca_object', 'object-breakdown', (id) => `
<div class="ca object-scene"><span class="micro top">OBJECT / OBSERVE BEFORE LABELING</span><div class="specimen"><i class="object"></i><i class="part a"></i><i class="part b"></i><i class="part c"></i></div><div class="notes"><div><b class="num">01</b><span data-edit>输入发生在这里</span></div><div><b class="num">02</b><span data-edit>阻力改变动作</span></div><div><b class="num">03</b><span data-edit>结果从边缘出现</span></div></div><h2 class="head" data-edit>拆开，但不忘记整体</h2></div>
<style>${root(id)}
#${id} .top{position:absolute;left:80px;top:65px;}#${id} .specimen{position:absolute;left:95px;top:150px;width:920px;height:790px;background:#e6dfd2;border:4px solid var(--fg);}#${id} .specimen .object{left:235px;top:135px;width:460px;height:540px;border-radius:30px;transform:rotate(-4deg);}#${id} .part{position:absolute;width:38px;height:38px;border-radius:50%;background:var(--accent);border:6px solid var(--paper);}#${id} .part.a{left:300px;top:290px;}#${id} .part.b{left:600px;top:450px;}#${id} .part.c{left:430px;top:670px;background:var(--accent-2);}#${id} .notes{position:absolute;left:1080px;top:180px;width:710px;}#${id} .notes div{display:grid;grid-template-columns:90px 1fr;gap:20px;padding:36px 0;border-top:3px solid var(--fg);}#${id} .notes b{font-size:27px;color:var(--accent);}#${id} .notes span{font-size:42px;font-weight:800;}#${id} .object-scene h2{position:absolute;left:1080px;bottom:90px;width:700px;font-size:76px;line-height:1;}
</style>`, (id) => `tl.from('#${id} .specimen',{scale:.94,autoAlpha:0,duration:.3},0);tl.from('#${id} .part',{scale:0,duration:.2,stagger:.12},.25);tl.from('#${id} .notes div',{x:60,autoAlpha:0,duration:.24,stagger:.1},.38);tl.from('#${id} h2',{autoAlpha:0,y:25,duration:.24},.68);`),

  'causal-chain': () => mk('ca_chain', 'causal-chain', (id) => `
<div class="ca chain"><span class="micro">CAUSE / ACTION / CONSEQUENCE</span><h2 class="head" data-edit>不是三个步骤<br/><b>是一条因果路线</b></h2><div class="nodes"><div class="n one"><i></i><b data-edit>输入</b><span>一个真实动作</span></div><i class="route r1"></i><div class="n two"><i></i><b data-edit>阻力</b><span>系统改变速度</span></div><i class="route r2"></i><div class="n three"><i></i><b data-edit>结果</b><span>反馈回到人</span></div></div></div>
<style>${root(id)}
#${id} .chain{background:var(--panel-2);color:#fff;}#${id} .chain>.micro{position:absolute;left:80px;top:65px;color:var(--accent);}#${id} .chain h2{position:absolute;left:80px;top:150px;font-size:91px;line-height:.96;}#${id} .chain h2 b{color:var(--accent);}#${id} .nodes{position:absolute;left:75px;right:75px;bottom:100px;height:470px;}#${id} .n{position:absolute;top:80px;width:390px;height:310px;padding:42px;background:var(--paper);color:var(--fg);}#${id} .n.one{left:0;}#${id} .n.two{left:610px;}#${id} .n.three{right:0;}#${id} .n i{display:block;width:72px;height:72px;border:8px solid var(--accent);border-radius:50%;}#${id} .n b{display:block;margin-top:40px;font-size:55px;}#${id} .n span{display:block;margin-top:18px;font-size:25px;color:var(--muted);}#${id} .nodes .route{top:220px;width:180px;}#${id} .r1{left:410px;}#${id} .r2{left:1020px;}
</style>`, (id) => `tl.from('#${id} h2,#${id}>.micro',{x:-45,autoAlpha:0,duration:.25,stagger:.08},0);tl.from('#${id} .n',{y:70,autoAlpha:0,duration:.25,stagger:.18},.24);tl.from('#${id} .route',{scaleX:0,duration:.22,stagger:.18},.42);`),

  'scale-shift': () => mk('ca_scale', 'scale-shift', (id) => `
<div class="ca scale"><div class="whole"><i class="object"></i><span class="micro">SYSTEM</span></div><div class="detail"><i class="object"></i><b class="ring"></b><span class="micro">DETAIL</span></div><i class="route"></i><div class="copy"><span class="micro">SCALE / KEEP ORIENTATION</span><h2 class="head" data-edit>从整体进入细节<br/><b>再带着答案回来</b></h2></div></div>
<style>${root(id)}
#${id} .whole{position:absolute;left:70px;top:70px;width:750px;height:940px;background:#e1dbcf;border:4px solid var(--fg);overflow:hidden;}#${id} .whole .object{left:160px;top:210px;width:430px;height:560px;border-radius:38px;}#${id} .whole span,#${id} .detail span{position:absolute;left:30px;bottom:26px;}#${id} .detail{position:absolute;left:940px;top:170px;width:880px;height:650px;background:#d1cabd;overflow:hidden;border:14px solid var(--accent);}#${id} .detail .object{left:-220px;top:-120px;width:1050px;height:980px;border-radius:90px;}#${id} .ring{position:absolute;right:90px;top:155px;width:260px;height:260px;border:16px solid var(--accent-2);border-radius:50%;}#${id} .scale>.route{left:760px;top:500px;width:260px;}#${id} .copy{position:absolute;left:970px;bottom:70px;width:800px;}#${id} .copy h2{margin-top:35px;font-size:63px;line-height:1;}#${id} .copy h2 b{color:var(--accent);}
</style>`, (id) => `tl.from('#${id} .whole',{x:-100,autoAlpha:0,duration:.3},0);tl.from('#${id} .route',{scaleX:0,duration:.25},.26);tl.from('#${id} .detail',{scale:.75,autoAlpha:0,duration:.34,ease:'power3.out'},.42);tl.from('#${id} .ring',{scale:0,duration:.22},.64);tl.from('#${id} .copy',{autoAlpha:0,y:25,duration:.23},.7);`),

  'misconception-turn': () => mk('ca_turn', 'misconception-turn', (id) => `
<div class="ca misconception"><span class="micro">REVISION / LET EVIDENCE INTERRUPT</span><div class="before"><span>原来的理解</span><h2 class="head" data-edit>速度决定结果</h2><i class="route"></i></div><i class="strike"></i><div class="after"><span>证据改变路线</span><h2 class="head" data-edit>真正改变结果的<br/><b>是交接方式</b></h2><i class="route"></i></div><div class="proof"><b class="num">03:42</b><span>来源片段 / 待用户确认</span></div></div>
<style>${root(id)}
#${id} .misconception>.micro{position:absolute;left:80px;top:65px;}#${id} .before{position:absolute;left:80px;top:190px;width:760px;height:650px;padding:55px;background:#e3ddd1;}#${id} .before span,#${id} .after>span{font-size:23px;font-weight:800;color:var(--muted);}#${id} .before h2{margin-top:150px;font-size:78px;}#${id} .before .route{left:70px;bottom:95px;width:520px;}#${id} .strike{position:absolute;left:95px;top:525px;width:760px;height:20px;background:var(--accent-2);transform:rotate(-8deg);}#${id} .after{position:absolute;right:75px;top:135px;width:890px;height:780px;padding:60px;background:var(--panel-2);color:#fff;}#${id} .after h2{margin-top:135px;font-size:80px;line-height:1;}#${id} .after h2 b{color:var(--accent);}#${id} .after .route{left:65px;bottom:105px;width:650px;}#${id} .proof{position:absolute;left:830px;bottom:55px;padding:22px 28px;background:var(--accent-2);color:#fff;}#${id} .proof b{font-size:30px;}#${id} .proof span{margin-left:18px;font-size:19px;}
</style>`, (id) => `tl.from('#${id} .before',{x:-100,autoAlpha:0,duration:.3},0);tl.from('#${id} .before .route',{scaleX:0,duration:.25},.2);tl.from('#${id} .strike',{scaleX:0,transformOrigin:'left',duration:.25},.45);tl.from('#${id} .after',{x:120,autoAlpha:0,duration:.33},.55);tl.from('#${id} .after .route',{scaleX:0,duration:.25},.76);`),

  'synthesis-map': () => mk('ca_synthesis', 'synthesis-map', (id) => `
<div class="ca synthesis"><div class="map"><div class="source"><i class="object"></i></div><i class="route one"></i><i class="route two"></i><span class="label a">输入</span><span class="label b">交接</span><span class="label c">结果</span></div><div class="copy"><span class="micro">SYNTHESIS / FEWER MARKS</span><h2 class="head" data-edit>结果不是终点<br/><b>它会回到下一次输入</b></h2><p data-edit>现在可以用一条路线重新看完整系统。</p></div><i class="correction"></i></div>
<style>${root(id)}
#${id} .synthesis{background:var(--panel-2);color:#fff;}#${id} .map{position:absolute;left:70px;top:70px;width:820px;height:940px;background:var(--paper);color:var(--fg);}#${id} .source{position:absolute;left:190px;top:160px;width:440px;height:590px;background:#d7d0c3;}#${id} .source .object{left:80px;top:90px;width:280px;height:400px;border-radius:30px;}#${id} .map .route{width:320px;}#${id} .map .one{left:80px;top:120px;transform:rotate(22deg);}#${id} .map .two{left:420px;bottom:120px;transform:rotate(164deg);}#${id} .map .label.a{left:35px;top:70px;}#${id} .map .label.b{right:30px;top:280px;}#${id} .map .label.c{left:60px;bottom:80px;}#${id} .copy{position:absolute;left:1010px;top:150px;width:790px;}#${id} .copy h2{margin-top:145px;font-size:91px;line-height:.96;}#${id} .copy h2 b{color:var(--accent);}#${id} .copy p{margin-top:70px;width:660px;font-size:28px;line-height:1.55;color:#ffffffb0;}#${id} .correction{position:absolute;left:940px;top:0;width:16px;height:790px;background:var(--accent-2);}
</style>`, (id) => `tl.from('#${id} .map',{x:-120,duration:.34},0);tl.from('#${id} .source',{scale:.9,autoAlpha:0,duration:.26},.2);tl.from('#${id} .route',{scaleX:0,duration:.28,stagger:.18},.38);tl.from('#${id} .label',{autoAlpha:0,duration:.2,stagger:.1},.55);tl.from('#${id} .copy>*',{x:45,autoAlpha:0,duration:.24,stagger:.08},.42);`),
};
