/** Retail Rush v2: product truth, verified offer hierarchy, density, proof, direct action. */
import { type Block, mk } from './shared';

const root = (id: string) => `
#${id} .rr{position:absolute;inset:0;overflow:hidden;background:var(--paper);color:var(--fg);font-family:var(--font-body);}
#${id} .head{font-family:var(--font-head);font-weight:950;letter-spacing:-.055em;}
#${id} .num{font-family:var(--font-num);font-variant-numeric:tabular-nums;}
#${id} .micro{font-family:var(--font-num);font-size:18px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;}
#${id} .product{position:absolute;width:410px;height:690px;border:8px solid var(--fg);background:#ece5d5;box-shadow:var(--shadow);}
#${id} .product::before{content:'';position:absolute;left:85px;right:85px;top:70px;height:100px;background:var(--fg);}
#${id} .product::after{content:'';position:absolute;left:65px;right:65px;bottom:80px;height:260px;background:var(--accent);}
#${id} .label{position:absolute;padding:14px 20px;background:var(--accent-2);border:5px solid var(--fg);box-shadow:6px 7px 0 var(--fg);font-size:23px;font-weight:950;}
#${id} .rule{position:absolute;height:18px;background:var(--accent);transform-origin:left center;}
#${id} [data-edit]{outline:none;}`;

export const cover: () => Block = () => mk('cv_rr2', '封面', (id) => `
<div class="rr cover"><div class="red"></div><div class="product"></div><div class="hand"></div><div class="title head" data-edit>零售脉冲</div><div class="english num">RETAIL RUSH</div><div class="label">PRODUCT FIRST</div><i class="rule"></i><div class="thesis micro">PRODUCT / BENEFIT / TERMS / ACTION</div></div>
<style>${root(id)}
#${id} .red{position:absolute;left:0;top:0;width:1050px;height:1080px;background:var(--accent);}#${id} .cover .product{right:250px;top:160px;transform:rotate(6deg) scale(1.15);}#${id} .hand{position:absolute;right:-60px;bottom:50px;width:800px;height:220px;background:#b78565;border:8px solid var(--fg);transform:rotate(-12deg);}#${id} .title{position:absolute;left:70px;top:210px;width:980px;color:#fff;font-size:180px;line-height:.88;}#${id} .english{position:absolute;left:80px;top:610px;color:#fff;font-size:31px;font-weight:900;letter-spacing:.2em;}#${id} .cover .label{left:900px;top:100px;}#${id} .cover .rule{left:70px;top:550px;width:820px;background:var(--accent-2);transform:rotate(-4deg);}#${id} .thesis{position:absolute;left:80px;bottom:70px;color:#fff;}
</style>`, (id) => `tl.from('#${id} .red',{x:-180,duration:.34},0);tl.from('#${id} .product',{y:-120,rotation:0,autoAlpha:0,duration:.32},.16);tl.from('#${id} .hand',{x:180,autoAlpha:0,duration:.3},.27);tl.from('#${id} .title,#${id} .english,#${id} .thesis',{x:-50,autoAlpha:0,duration:.23,stagger:.06},.3);tl.from('#${id} .label',{scale:0,duration:.2},.56);`);

export const blocks: Record<string, () => Block> = {
  'product-hit': () => mk('rr_hit', 'product-hit', (id) => `
<div class="rr hit"><div class="field"></div><div class="hand"></div><div class="product"></div><div class="copy"><span class="micro">PRODUCT HIT / IDENTITY IN ONE SECOND</span><h2 class="head" data-edit>拿起它<br/><b>就知道怎么用</b></h2><p data-edit>真实包装、真实动作、真实材质先出现。</p></div><div class="label">看清产品</div><i class="rule"></i></div>
<style>${root(id)}
#${id} .field{position:absolute;left:0;top:0;width:920px;height:1080px;background:var(--accent);}#${id} .hit .product{left:320px;top:170px;transform:rotate(-5deg) scale(1.08);}#${id} .hand{position:absolute;left:-140px;bottom:160px;width:800px;height:210px;background:#b98567;border:8px solid var(--fg);transform:rotate(15deg);}#${id} .copy{position:absolute;left:1030px;top:145px;width:780px;}#${id} .copy h2{margin-top:130px;font-size:99px;line-height:.94;}#${id} .copy h2 b{color:var(--accent);}#${id} .copy p{margin-top:70px;font-size:28px;line-height:1.55;}#${id} .hit .label{left:760px;top:130px;}#${id} .hit .rule{left:1030px;bottom:130px;width:670px;}
</style>`, (id) => `tl.from('#${id} .field',{x:-160,duration:.34},0);tl.from('#${id} .product',{y:-110,rotation:0,autoAlpha:0,duration:.3},.16);tl.from('#${id} .hand',{x:-130,autoAlpha:0,duration:.28},.3);tl.from('#${id} .copy>*',{x:55,autoAlpha:0,duration:.23,stagger:.07},.34);tl.from('#${id} .label',{scale:0,duration:.2},.58);`),

  'offer-lockup': () => mk('rr_offer', 'offer-lockup', (id) => `
<div class="rr offer"><div class="black"></div><div class="product"></div><div class="info"><span class="micro">VERIFIED OFFER / TERMS MUST BE SUPPLIED</span><h2 class="head" data-edit>真实套装</h2><div class="price"><sup>¥</sup><b class="num" data-edit>199</b><span>示例价格<br/>发布前确认</span></div><div class="terms">2 件套 / 适用版本待确认 / 不虚构原价</div><div class="cta head" data-edit>现在去看</div></div><div class="label">ONE CLEAR ACTION</div></div>
<style>${root(id)}
#${id} .black{position:absolute;left:0;top:0;width:760px;height:1080px;background:var(--panel-2);}#${id} .offer .product{left:175px;top:190px;transform:rotate(4deg) scale(1.05);}#${id} .info{position:absolute;left:850px;top:85px;width:960px;}#${id} .info h2{margin-top:80px;font-size:90px;}#${id} .price{display:flex;align-items:flex-end;margin-top:60px;border-top:12px solid var(--accent);padding-top:35px;}#${id} .price sup{font-size:80px;font-weight:900;}#${id} .price b{font-size:330px;line-height:.8;letter-spacing:-.08em;}#${id} .price span{margin-left:40px;font-size:23px;line-height:1.4;}#${id} .terms{margin-top:60px;padding:22px 28px;border:4px solid var(--fg);font-size:24px;}#${id} .cta{display:inline-block;margin-top:50px;padding:25px 40px;background:var(--accent-2);font-size:58px;}#${id} .offer .label{left:600px;top:120px;}
</style>`, (id) => `tl.from('#${id} .black',{x:-150,duration:.34},0);tl.from('#${id} .product',{y:100,rotation:0,autoAlpha:0,duration:.3},.15);tl.from('#${id} .info>*',{x:60,autoAlpha:0,duration:.24,stagger:.08},.28);tl.from('#${id} .price b',{innerText:0,snap:{innerText:1},duration:.65},.45);tl.from('#${id} .label',{scale:0,duration:.2},.62);`),

  'benefit-stack': () => mk('rr_benefits', 'benefit-stack', (id) => `
<div class="rr benefits"><span class="micro">BENEFIT RUN / ONE SOURCE BEAT EACH</span><div class="product"></div><div class="benefit one"><b class="num">01</b><h3 class="head" data-edit>一按即开</h3><span>真实动作片段</span></div><div class="benefit two"><b class="num">02</b><h3 class="head" data-edit>折叠收好</h3><span>真实体积变化</span></div><div class="benefit three"><b class="num">03</b><h3 class="head" data-edit>放进日常</h3><span>真实使用场景</span></div><i class="rule"></i></div>
<style>${root(id)}
#${id} .benefits>.micro{position:absolute;left:75px;top:55px;}#${id} .benefits .product{left:110px;top:210px;transform:rotate(-5deg);}#${id} .benefit{position:absolute;left:650px;right:70px;height:235px;padding:35px 45px;border-top:8px solid var(--fg);display:grid;grid-template-columns:100px 1fr 300px;align-items:center;}#${id} .benefit.one{top:130px;}#${id} .benefit.two{top:410px;background:var(--accent);color:#fff;}#${id} .benefit.three{top:690px;}#${id} .benefit b{font-size:34px;}#${id} .benefit h3{font-size:70px;}#${id} .benefit span{font-size:25px;}#${id} .benefits>.rule{left:500px;top:120px;width:18px;height:850px;background:var(--accent);}
</style>`, (id) => `tl.from('#${id} .product',{x:-120,rotation:0,autoAlpha:0,duration:.3},0);tl.from('#${id} .rule',{scaleY:0,transformOrigin:'top',duration:.27},.18);tl.from('#${id} .benefit',{x:130,autoAlpha:0,duration:.26,stagger:.13},.28);`),

  'variant-run': () => mk('rr_variants', 'variant-run', (id) => `
<div class="rr variants"><div class="red"></div><div class="copy"><span class="micro">VARIANT RUN / REAL DIFFERENCES</span><h2 class="head" data-edit>同一件事<br/><b>三种选择</b></h2><p>颜色、尺寸或版本必须来自真实产品。</p></div><div class="lineup"><div class="v a"><i class="product"></i><b>01 / 红</b></div><div class="v b"><i class="product"></i><b>02 / 黑</b></div><div class="v c"><i class="product"></i><b>03 / 青</b></div></div><div class="label">SELECT THE REAL ONE</div></div>
<style>${root(id)}
#${id} .red{position:absolute;left:0;top:0;width:650px;height:1080px;background:var(--accent);}#${id} .copy{position:absolute;left:70px;top:100px;width:520px;color:#fff;}#${id} .copy h2{margin-top:120px;font-size:92px;line-height:.9;}#${id} .copy h2 b{color:var(--accent-2);}#${id} .copy p{margin-top:70px;font-size:26px;line-height:1.5;}#${id} .lineup{position:absolute;left:740px;right:60px;top:130px;bottom:90px;display:flex;gap:35px;align-items:flex-end;}#${id} .v{position:relative;flex:1;height:780px;border-bottom:10px solid var(--fg);}#${id} .v .product{left:50%;top:50px;transform:translateX(-50%) scale(.75);}#${id} .v.b .product::after{background:#181818;}#${id} .v.c .product::after{background:#2ca58d;}#${id} .v b{position:absolute;left:20px;bottom:25px;font-family:var(--font-num);font-size:24px;}#${id} .variants .label{right:70px;top:70px;}
</style>`, (id) => `tl.from('#${id} .red',{x:-150,duration:.34},0);tl.from('#${id} .copy>*',{x:-45,autoAlpha:0,duration:.23,stagger:.07},.18);tl.from('#${id} .v',{y:130,autoAlpha:0,duration:.27,stagger:.12},.28);tl.from('#${id} .label',{scale:0,duration:.2},.62);`),

  'proof-burst': () => mk('rr_proof', 'proof-burst', (id) => `
<div class="rr proof"><div class="source"><div class="before"></div><div class="after"></div><span class="num">REAL SOURCE / RESULT HOLD</span></div><div class="copy"><span class="micro">PROOF / LOWER THE PRESSURE</span><h2 class="head" data-edit>先看结果<br/><b>再听结论</b></h2><p data-edit>画面证明不了的，不用设计假装证明。</p><div class="claim">用户确认后的真实证据</div></div><i class="rule"></i></div>
<style>${root(id)}
#${id} .proof{background:var(--panel-2);color:#fff;}#${id} .source{position:absolute;left:70px;top:70px;width:1050px;height:940px;background:#e8dfcf;color:var(--fg);display:flex;gap:20px;padding:70px;}#${id} .before,#${id} .after{flex:1;background:linear-gradient(145deg,#c2ae96,#f2d9bd 58%,#76655b);border:8px solid var(--fg);}#${id} .after{filter:contrast(1.08) saturate(1.1);}#${id} .source span{position:absolute;left:70px;bottom:25px;font-size:18px;}#${id} .copy{position:absolute;left:1220px;top:140px;width:620px;}#${id} .copy h2{margin-top:130px;font-size:90px;line-height:.92;}#${id} .copy h2 b{color:var(--accent-2);}#${id} .copy p{margin-top:65px;font-size:27px;line-height:1.55;color:#ffffffb2;}#${id} .claim{margin-top:75px;padding:28px;background:var(--paper);color:var(--fg);font-size:28px;font-weight:900;}#${id} .proof>.rule{left:1165px;top:0;width:16px;height:820px;background:var(--accent);}
</style>`, (id) => `tl.from('#${id} .source',{x:-140,duration:.34},0);tl.from('#${id} .before,#${id} .after',{scale:.9,autoAlpha:0,duration:.27,stagger:.12},.2);tl.from('#${id} .rule',{scaleY:0,transformOrigin:'top',duration:.25},.35);tl.from('#${id} .copy>*',{x:55,autoAlpha:0,duration:.23,stagger:.08},.4);`),

  'checkout-release': () => mk('rr_release', 'checkout-release', (id) => `
<div class="rr release"><div class="red"></div><div class="product"></div><div class="copy"><span class="micro">CHECKOUT RELEASE / ESSENTIAL FACTS ONLY</span><h2 class="head" data-edit>看清产品<br/><b>确认条款</b><br/>再去行动</h2><div class="terms">价格 / 日期 / 适用范围 / 发布前确认</div><div class="cta head" data-edit>现在去看</div></div><div class="label">ONE PRODUCT / ONE ACTION</div></div>
<style>${root(id)}
#${id} .release{background:var(--accent);}#${id} .red{position:absolute;left:0;top:0;width:800px;height:1080px;background:var(--paper);}#${id} .release .product{left:190px;top:180px;transform:rotate(-4deg) scale(1.08);}#${id} .copy{position:absolute;left:900px;top:100px;width:850px;color:#fff;}#${id} .copy h2{margin-top:120px;font-size:102px;line-height:.88;}#${id} .copy h2 b{color:var(--accent-2);}#${id} .terms{margin-top:60px;padding:22px 28px;border:5px solid #fff;font-size:24px;}#${id} .cta{display:inline-block;margin-top:55px;padding:28px 42px;background:var(--accent-2);color:var(--fg);font-size:64px;}#${id} .release .label{left:690px;top:90px;}
</style>`, (id) => `tl.from('#${id} .red',{x:-150,duration:.34},0);tl.from('#${id} .product',{y:120,rotation:0,autoAlpha:0,duration:.3},.18);tl.from('#${id} .copy>*',{x:60,autoAlpha:0,duration:.24,stagger:.08},.28);tl.from('#${id} .label',{scale:0,duration:.2},.58);`),
};
