/** Social Cutout v2: people-first phone energy, real artifacts, reaction, chorus, release. */
import { type Block, mk } from './shared';

const root = (id: string) => `
#${id} .sc{position:absolute;inset:0;overflow:hidden;background:var(--paper);color:var(--fg);font-family:var(--font-body);}
#${id} .head{font-family:var(--font-head);font-weight:950;letter-spacing:-.05em;}
#${id} .num{font-family:var(--font-num);font-variant-numeric:tabular-nums;}
#${id} .micro{font-family:var(--font-num);font-size:18px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;}
#${id} .person{position:absolute;width:420px;height:780px;filter:drop-shadow(12px 14px 0 rgb(23 23 25 / .24));}
#${id} .person .face{position:absolute;left:105px;top:10px;width:210px;height:235px;border-radius:48%;background:#9d6b50;border:10px solid var(--paper);}
#${id} .person .body{position:absolute;left:18px;top:225px;width:385px;height:560px;border-radius:180px 180px 0 0;background:#405a76;border:10px solid var(--paper);}
#${id} .photo{position:absolute;background:linear-gradient(145deg,#c9b9a6,#f2dcc6 58%,#765d55);border:14px solid var(--paper);box-shadow:var(--shadow);overflow:hidden;}
#${id} .sticker{position:absolute;padding:15px 22px;background:var(--accent-2);border:5px solid var(--fg);box-shadow:6px 7px 0 var(--fg);font-size:24px;font-weight:950;transform:rotate(-4deg);}
#${id} .marker{position:absolute;height:18px;background:var(--accent);transform-origin:left center;}
#${id} [data-edit]{outline:none;}`;

export const cover: () => Block = () => mk('cv_sc2', '封面', (id) => `
<div class="sc cover"><div class="red"></div><div class="photo a"></div><div class="photo b"></div><div class="person"><i class="face"></i><i class="body"></i></div><div class="title head" data-edit>社交拼场</div><div class="english num">SOCIAL CUTOUT</div><div class="sticker">PEOPLE WERE HERE</div><i class="marker"></i><div class="thesis micro">PEOPLE / TRACE / REACTION / CHORUS</div></div>
<style>${root(id)}
#${id} .red{position:absolute;left:0;top:0;width:850px;height:1080px;background:var(--accent);}#${id} .cover .photo.a{right:80px;top:90px;width:620px;height:430px;transform:rotate(5deg);}#${id} .cover .photo.b{right:480px;bottom:70px;width:540px;height:380px;transform:rotate(-7deg);}#${id} .cover .person{right:180px;bottom:-20px;}#${id} .title{position:absolute;left:75px;top:210px;width:880px;font-size:180px;line-height:.88;color:#fff;}#${id} .english{position:absolute;left:85px;top:610px;font-size:31px;font-weight:900;letter-spacing:.2em;color:#fff;}#${id} .cover .sticker{left:690px;top:120px;}#${id} .cover .marker{left:75px;top:550px;width:730px;transform:rotate(-5deg);background:var(--accent-2);}#${id} .thesis{position:absolute;left:85px;bottom:70px;color:#fff;}
</style>`, (id) => `tl.from('#${id} .red',{x:-160,duration:.34},0);tl.from('#${id} .photo',{y:100,rotation:0,autoAlpha:0,duration:.28,stagger:.1},.16);tl.from('#${id} .person',{y:120,autoAlpha:0,duration:.3},.3);tl.from('#${id} .title,#${id} .english,#${id} .thesis',{x:-45,autoAlpha:0,duration:.23,stagger:.06},.32);tl.from('#${id} .sticker',{scale:0,rotation:8,duration:.22},.55);`);

export const blocks: Record<string, () => Block> = {
  'crew-intro': () => mk('sc_crew', 'crew-intro', (id) => `
<div class="sc crew"><div class="word head" data-edit>我们<br/>都在场</div><div class="p p1"><div class="person"><i class="face"></i><i class="body"></i></div><b>阿青 / 镜头外</b></div><div class="p p2"><div class="person"><i class="face"></i><i class="body"></i></div><b>小海 / 第一个笑</b></div><div class="p p3"><div class="person"><i class="face"></i><i class="body"></i></div><b>米粒 / 带来声音</b></div><div class="sticker">不是名单，是关系</div><span class="micro">CREW INTRO / DISTINCT PRESENCE</span></div>
<style>${root(id)}
#${id} .crew{background:var(--panel-2);color:#fff;}#${id} .word{position:absolute;left:70px;top:100px;font-size:150px;line-height:.82;color:var(--accent-2);transform:rotate(-4deg);}#${id} .p{position:absolute;width:470px;height:820px;}#${id} .p .person{left:20px;top:0;}#${id} .p b{position:absolute;left:25px;bottom:10px;padding:14px 20px;background:var(--paper);color:var(--fg);font-size:25px;transform:rotate(-3deg);}#${id} .p1{left:480px;top:170px;transform:rotate(-4deg);}#${id} .p2{left:930px;top:70px;transform:rotate(3deg);}#${id} .p2 .body{background:#a74139;}#${id} .p3{right:40px;top:210px;transform:rotate(-2deg);}#${id} .p3 .body{background:#3d725d;}#${id} .crew .sticker{left:80px;bottom:170px;color:var(--fg);}#${id} .crew>.micro{position:absolute;left:80px;bottom:70px;}
</style>`, (id) => `tl.from('#${id} .p',{y:130,rotation:0,autoAlpha:0,duration:.28,stagger:.12},0);tl.from('#${id} .word',{x:-80,autoAlpha:0,duration:.28},.22);tl.from('#${id} .sticker',{scale:0,rotation:7,duration:.22},.55);`),

  'cutout-reaction': () => mk('sc_reaction', 'cutout-reaction', (id) => `
<div class="sc reaction"><div class="photo"></div><div class="person"><i class="face"></i><i class="body"></i></div><div class="quote head" data-edit>“等等，<br/>这真的有用。”</div><i class="marker"></i><div class="sticker">真实反应 / 00:07</div><span class="micro">CUTOUT REACTION / LET THE LOOK LAND</span></div>
<style>${root(id)}
#${id} .reaction .photo{left:-70px;top:-40px;width:1120px;height:1160px;border-width:0;}#${id} .reaction .person{left:560px;top:170px;transform:scale(1.15) rotate(4deg);}#${id} .quote{position:absolute;left:1030px;top:210px;width:790px;font-size:112px;line-height:.9;}#${id} .reaction .marker{left:1050px;top:650px;width:650px;transform:rotate(-7deg);}#${id} .reaction .sticker{right:110px;bottom:190px;}#${id} .reaction>.micro{position:absolute;right:90px;bottom:75px;}
</style>`, (id) => `tl.from('#${id} .photo',{x:-150,duration:.34},0);tl.from('#${id} .person',{x:120,rotation:0,autoAlpha:0,duration:.3},.18);tl.from('#${id} .quote',{x:70,autoAlpha:0,duration:.27},.35);tl.from('#${id} .marker',{scaleX:0,duration:.23},.52);tl.from('#${id} .sticker',{scale:0,duration:.2},.63);`),

  'receipt-stack': () => mk('sc_receipts', 'receipt-stack', (id) => `
<div class="sc receipts"><div class="copy"><span class="micro">TRACE STACK / REAL ARTIFACTS</span><h2 class="head" data-edit>一晚留下的<br/><b>不是一张照片</b></h2><p>票根、消息、包装和现场声音共同证明发生过。</p></div><div class="art ticket"><b class="num">ENTRY / 21:30</b><i></i><span>地点待确认</span></div><div class="art message"><b>“我们已经到了”</b><span>真实消息需授权</span></div><div class="photo"></div><div class="sticker">SOURCE, NOT DECORATION</div></div>
<style>${root(id)}
#${id} .copy{position:absolute;left:70px;top:90px;width:790px;}#${id} .copy h2{margin-top:130px;font-size:99px;line-height:.93;}#${id} .copy h2 b{color:var(--accent);}#${id} .copy p{margin-top:65px;width:650px;font-size:27px;line-height:1.55;}#${id} .art{position:absolute;padding:45px;background:#fff;border:5px solid var(--fg);box-shadow:var(--shadow);}#${id} .ticket{left:930px;top:100px;width:760px;height:300px;transform:rotate(5deg);}#${id} .ticket b{font-size:33px;}#${id} .ticket i{display:block;margin-top:55px;border-top:8px dashed var(--fg);}#${id} .ticket span{display:block;margin-top:38px;font-size:24px;}#${id} .message{left:1080px;top:430px;width:650px;height:240px;transform:rotate(-5deg);background:var(--accent-2);}#${id} .message b{display:block;font-size:45px;}#${id} .message span{display:block;margin-top:45px;font-size:22px;}#${id} .receipts .photo{left:850px;bottom:30px;width:530px;height:380px;transform:rotate(8deg);}#${id} .receipts .sticker{left:640px;bottom:120px;}
</style>`, (id) => `tl.from('#${id} .copy>*',{x:-45,autoAlpha:0,duration:.23,stagger:.07},0);tl.from('#${id} .art,#${id} .photo',{y:120,rotation:0,autoAlpha:0,duration:.27,stagger:.11},.2);tl.from('#${id} .sticker',{scale:0,rotation:6,duration:.2},.58);`),

  'rhythm-wall': () => mk('sc_wall', 'rhythm-wall', (id) => `
<div class="sc wall"><div class="photo one"></div><div class="photo two"></div><div class="photo three"></div><div class="person"><i class="face"></i><i class="body"></i></div><div class="slam head" data-edit>现在<br/>轮到我们</div><div class="sticker a">PLACE</div><div class="sticker b">VOICE</div><div class="sticker c">MOVE</div><i class="marker"></i></div>
<style>${root(id)}
#${id} .wall{background:var(--accent);}#${id} .wall .photo.one{left:40px;top:40px;width:540px;height:360px;transform:rotate(-5deg);}#${id} .wall .photo.two{left:520px;top:470px;width:580px;height:420px;transform:rotate(6deg);}#${id} .wall .photo.three{right:-50px;top:30px;width:650px;height:440px;transform:rotate(4deg);}#${id} .wall .person{right:260px;bottom:-90px;transform:scale(1.05) rotate(-5deg);}#${id} .slam{position:absolute;left:80px;top:410px;font-size:145px;line-height:.78;color:#fff;transform:rotate(-4deg);}#${id} .wall .sticker.a{left:130px;top:100px;}#${id} .wall .sticker.b{left:820px;top:120px;transform:rotate(7deg);}#${id} .wall .sticker.c{right:100px;top:470px;transform:rotate(-8deg);}#${id} .wall>.marker{left:60px;bottom:130px;width:860px;background:var(--accent-2);transform:rotate(5deg);}
</style>`, (id) => `tl.from('#${id} .photo',{scale:.75,rotation:0,autoAlpha:0,duration:.25,stagger:.1},0);tl.from('#${id} .person',{y:150,autoAlpha:0,duration:.28},.2);tl.from('#${id} .slam',{x:-90,autoAlpha:0,duration:.25},.3);tl.from('#${id} .sticker',{scale:0,duration:.18,stagger:.08},.48);tl.from('#${id} .marker',{scaleX:0,duration:.2},.64);`),

  'comment-pulse': () => mk('sc_comment', 'comment-pulse', (id) => `
<div class="sc comment"><div class="night"></div><div class="photo"><div class="person"><i class="face"></i><i class="body"></i></div></div><div class="bubble"><span class="micro">REAL COMMENT / PERMISSION REQUIRED</span><h2 class="head" data-edit>“这不是给<br/>我们做的吧？”</h2></div><i class="reply"></i><div class="answer head" data-edit>那就现在<br/><b>重新回答</b></div><div class="sticker">另一种声音进入</div></div>
<style>${root(id)}
#${id} .comment{background:var(--panel-2);color:#fff;}#${id} .comment .photo{left:70px;top:70px;width:720px;height:940px;}#${id} .comment .photo .person{left:160px;top:180px;}#${id} .bubble{position:absolute;left:870px;top:100px;width:860px;padding:65px;background:var(--paper);color:var(--fg);transform:rotate(2deg);}#${id} .bubble h2{margin-top:80px;font-size:88px;line-height:.95;}#${id} .reply{position:absolute;left:940px;top:650px;width:760px;height:18px;background:var(--accent-2);transform:rotate(-5deg);}#${id} .answer{position:absolute;left:950px;top:735px;font-size:75px;line-height:.9;}#${id} .answer b{color:var(--accent-2);}#${id} .comment .sticker{right:80px;bottom:55px;color:var(--fg);}
</style>`, (id) => `tl.from('#${id} .photo',{x:-130,duration:.34},0);tl.from('#${id} .bubble',{x:150,rotation:0,autoAlpha:0,duration:.3},.2);tl.from('#${id} .reply',{scaleX:0,duration:.23},.5);tl.from('#${id} .answer',{y:40,autoAlpha:0,duration:.24},.6);tl.from('#${id} .sticker',{scale:0,duration:.2},.72);`),

  'group-release': () => mk('sc_release', 'group-release', (id) => `
<div class="sc release"><div class="wide"><div class="person p1"><i class="face"></i><i class="body"></i></div><div class="person p2"><i class="face"></i><i class="body"></i></div><div class="person p3"><i class="face"></i><i class="body"></i></div></div><div class="copy"><span class="micro">GROUP RELEASE / LESS COLLAGE</span><h2 class="head" data-edit>最后记住的<br/><b>应该是人</b></h2><p data-edit>让现场声音和一个直接邀请完成结尾。</p><div class="sticker">一起去现场</div></div><i class="marker"></i></div>
<style>${root(id)}
#${id} .wide{position:absolute;left:0;top:0;width:1160px;height:1080px;background:linear-gradient(145deg,#857066,#d8b79e 60%,#4e5860);overflow:hidden;}#${id} .wide .person{top:260px;transform:scale(.95);}#${id} .wide .p1{left:30px;}#${id} .wide .p2{left:360px;}#${id} .wide .p2 .body{background:#9b403a;}#${id} .wide .p3{left:690px;}#${id} .wide .p3 .body{background:#426c55;}#${id} .copy{position:absolute;left:1250px;top:145px;width:580px;}#${id} .copy h2{margin-top:130px;font-size:85px;line-height:.94;}#${id} .copy h2 b{color:var(--accent);}#${id} .copy p{margin-top:65px;font-size:27px;line-height:1.5;}#${id} .copy .sticker{position:relative;display:inline-block;margin-top:75px;}#${id} .release>.marker{left:1120px;top:0;width:18px;height:830px;background:var(--accent);}
</style>`, (id) => `tl.from('#${id} .wide',{x:-160,duration:.35},0);tl.from('#${id} .person',{y:100,autoAlpha:0,duration:.26,stagger:.1},.18);tl.from('#${id} .marker',{scaleY:0,transformOrigin:'top',duration:.26},.3);tl.from('#${id} .copy>*',{x:55,autoAlpha:0,duration:.24,stagger:.08},.38);`),
};
